### ISSUE TITLE
Double page refresh when generating the report

### ISSUE THREAD

**Issue by damian1976** [allegro/ralph_pricing#420]
The scenario is as follows (will be difficult to reproduce at your site):
- I go to /scrooge/pricing-objects-usages-report and select my custom usage type (Active Energy)
- Press **Update** button
-  It looks like the message "**Calculating the report. Please wait...**" which is displayed after button is presse appears for the second time one after another. In other words it look like the report is generated twice but is displayed after the message appears for the second time.

The worker section in **supervisord.conf**  looks like this:
```
[program:rqworker]
command=/home/ralph/bin/ralph rqworker default scrooge_report scrooge_costs scrooge_collect
priority=12
numprocs=4
process_name=rq%(process_num)s
user=ralph
group=ralph
```

and the piece of log related to described behaviour is as follows:

```
[02.04.2015 11:50:51,488] INFO    [MainProcess 13585] report_pricing_objects_usages - Generating service environments dailyusages report from 2015-03-26 to 2015-04-02
[02.04.2015 11:50:51,522] INFO    [MainProcess 13585] base_report - Report generated
[02.04.2015 11:51:02,602] INFO    [MainProcess 13586] report_pricing_objects_usages - Generating service environments dailyusages report from 2015-03-26 to 2015-04-02
[02.04.2015 11:51:02,637] INFO    [MainProcess 13586] base_report - Report generated
[02.04.2015 11:51:14,021] ERROR   [MainProcess 21756] base - Internal Server Error: /scrooge/pricing-objects-usages-report/
Traceback (most recent call last):
  File "/home/ralph/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 109, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/ralph/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 20, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/ralph/ralph_scrooge/src/ralph_scrooge/utils/security.py", line 24, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/ralph/local/lib/python2.7/site-packages/django/views/generic/base.py", line 48, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ralph/ralph_develop/src/ralph/account/models.py", line 297, in inner_decorator
    return func(self, *args, **kwargs)
  File "/home/ralph/ralph_scrooge/src/ralph_scrooge/views/base.py", line 28, in dispatch
    return super(Base, self).dispatch(*args, **kwargs)
  File "/home/ralph/ralph_develop/src/ralph/ui/views/common.py", line 250, in dispatch
    return super(MenuMixin, self).dispatch(request, *args, **kwargs)
  File "/home/ralph/local/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ralph/ralph_scrooge/src/ralph_scrooge/views/base_report.py", line 93, in get
    **self.form.cleaned_data
  File "/home/ralph/ralph_scrooge/src/ralph_scrooge/views/base_report.py", line 146, in run_on_worker
    return self.report.run_on_worker(**kwargs)
  File "/home/ralph/ralph_scrooge/src/ralph_scrooge/utils/worker_job.py", line 54, in run_on_worker
    job = Job.fetch(job_id, connection)
  File "/home/ralph/local/lib/python2.7/site-packages/rq/job.py", line 278, in fetch
    job.refresh()
  File "/home/ralph/local/lib/python2.7/site-packages/rq/job.py", line 377, in refresh
    raise NoSuchJobError('No such job: %s' % (key,))
NoSuchJobError: No such job: rq:job:7ba2c4c9-01df-4b6f-8159-cbfc586c663b
```

**Comment by mkurek** [comment]
may be related to gunicorn (i've tested it locally on Docker image and using runserver everything works fine but using gunicorn somehow cache is forgetting task result).
